#!/bin/bash
# D-LinkUtility-Package
# Copyright (c) 2021, 2022 chris1111. All Right Reserved
# Credit: Acidanthera
# Permission to use, copy, modify, and/or distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
# Vars
apptitle="D-LinkUtility-Package"
version="1.0"
# Set Icon directory and file 
export ICNS=$(dirname "${0}")
iconfile="$ICNS/AppIcon.icns"
Sleep 1
echo "DETAILS:HIDE"
echo "PROGRESS:0"
response=$(osascript -e 'tell app "System Events" to display dialog "
This utility Working for macOS Catalina, Big Sur 11, Monterey 12, Ventura 13 only!

Select an option 
Install Utility or Uninstall\nCancel for Quit" buttons {"Cancel", "Install Utility" ,"Uninstall Utility"} default button 2 with title "'"$apptitle"' '"$version"'" with icon POSIX file "'"$iconfile"'"  ')

action=$(echo $response | cut -d ':' -f2)

# Exit if Canceled
if [ ! "$action" ] ; then
  osascript -e 'display notification "Program closing" with title "'"$apptitle"'" subtitle "User cancelled"'
echo "QUITAPP"
  exit 0
fi

osascript <<EOD
  tell application "D-LinkUtility-Package"
      activate
  end tell
EOD
if [ "$action" == "Uninstall Utility" ] ; then
Open ./Input/UninstallD-LinkUtility.pkg
Sleep 1
echo "QUITAPP"
fi

response=$(osascript -e 'tell app "System Events" to display dialog "
Select an option 
Install with Bootloader or Install on /Library/Extensions\n" buttons {"Install OC", "Install Clover" ,"Install /Library/Extensions"} default button 1 with title "'"$apptitle"' '"$version"'" with icon POSIX file "'"$iconfile"'"  ')

action=$(echo $response | cut -d ':' -f2)




osascript <<EOD
  tell application "D-LinkUtility-Package"
      activate
  end tell
EOD


if [ "$action" == "Install OC" ] ; then
  osascript -e 'display notification "Program Start" with title "'"$apptitle"'" subtitle "User Select Install OC"'
echo "DETAILS:HIDE"
echo "PROGRESS:0"
sleep 1
echo "PROGRESS:10"
sleep 1
echo "PROGRESS:20"
sleep 1
echo "PROGRESS:30"
echo "Install Progres."
Sleep 1
echo "PROGRESS:40"
sleep 1
echo "PROGRESS:50"
sleep 1
echo "PROGRESS:60"
sleep 2
echo "PROGRESS:80"
sleep 1
osascript <<EOD
  tell application "D-LinkUtility-Package"
      activate
  end tell
EOD
sleep 1
# Select Confirm Install
response=$(osascript -e 'tell app "System Events" to display dialog "
- - - - - - - - - - - - - - - - - - - - - - - - - -
By confirming that you agree to install this program on your current system, you will need to enter your password to complete the installation.
This program will install RT2870USBWirelessDriver.kext 
EFI System Partition /EFI/OC/kexts.
After Installation Plug the Mediatek USB adapter then Restart the Mac!		
- - - - - - - - - - - - - - - - - - - - - - - - - -
Cancel for Exit" buttons {"Cancel","Confirm Install"} default button 2 with title "'"$apptitle"' '"$version"'" with icon POSIX file "'"$iconfile"'"  ')

action=$(echo $response | cut -d ':' -f2)

 #  Post Installer is user select Confirm Install
  if [ "$action" == "Confirm Install" ] ; then
    # run the pkg
    echo "Install Package"
    cp -r ./Input/Wifi-Utility.app /Applications
    osascript -e 'tell application "System Events" to make login item at end with properties {path:"/Applications/Wifi-Utility.app", hidden:false}'
    Sleep 1
    Open -a /Applications/Wifi-Utility.app
    echo "Install OCD-LinkUtility.pkg"
    osascript -e 'do shell script "installer -allowUntrusted -verboseR -pkg ./Input/OCD-LinkUtility.pkg -target /" with administrator privileges'
echo "Install Utility-Package Done"
Sleep 1
cp -r ./Input/ActiveProfileSetting.plist /Private/tmp
Sleep 1
cp -r ./Input/AdvancedProfileSetting.plist $HOME/Library/Preferences
Sleep 1
echo "Open PlistEdit"
osascript ./Input/PlistEdit.app
echo "PROGRESS:90"
sleep 1
echo "PROGRESS:100"
echo "DETAILS:SHOW"
Sleep 3
osascript <<EOD
  tell application "D-LinkUtility-Package"
      activate
  end tell
EOD
echo "Install Done"

  fi


# Exit if Canceled
if [ "$action" == "Cancel" ] ; then
  osascript -e 'do shell script "afplay './Sound/Funk.aiff' &> /dev/null &"'
  osascript -e 'display notification "Program closing" with title "'"$apptitle"'" subtitle "User cancelled"'
  echo "Program closing in 2 seconds User cancelled"
  Sleep 2
  echo "QUITAPP"
  exit 0
fi

fi

if [ "$action" == "Install Clover" ] ; then
  osascript -e 'display notification "Program Start" with title "'"$apptitle"'" subtitle "User Select Install Clover"'
echo "DETAILS:HIDE"
echo "PROGRESS:0"
sleep 1
echo "PROGRESS:10"
sleep 1
echo "PROGRESS:20"
sleep 1
echo "PROGRESS:30"
echo "Install Progres."
Sleep 1
echo "PROGRESS:40"
sleep 1
echo "PROGRESS:50"
sleep 1
echo "PROGRESS:60"
sleep 2
echo "PROGRESS:80"
sleep 1
osascript <<EOD
  tell application "D-LinkUtility-Package"
      activate
  end tell
EOD
sleep 1
# Select Confirm Install
response=$(osascript -e 'tell app "System Events" to display dialog "
- - - - - - - - - - - - - - - - - - - - - - - - - -
By confirming that you agree to install this program on your current system, you will need to enter your password to complete the installation.
This program will install RT2870USBWirelessDriver.kext 
EFI System Partition /EFI/CLOVER/kexts/Other.
After Installation Plug the Mediatek USB adapter then Restart the Mac!		
- - - - - - - - - - - - - - - - - - - - - - - - - -
Cancel for Exit" buttons {"Cancel","Confirm Install"} default button 2 with title "'"$apptitle"' '"$version"'" with icon POSIX file "'"$iconfile"'"  ')

action=$(echo $response | cut -d ':' -f2)

 #  Post Installer is user select Confirm Install
  if [ "$action" == "Confirm Install" ] ; then
    # run the pkg
    echo "Install Package"
    cp -r ./Input/Wifi-Utility.app /Applications
    osascript -e 'tell application "System Events" to make login item at end with properties {path:"/Applications/Wifi-Utility.app", hidden:false}'
    Sleep 1
    Open -a /Applications/Wifi-Utility.app
    echo "Install CloverD-LinkUtility.pkg"
    osascript -e 'do shell script "installer -allowUntrusted -verboseR -pkg ./Input/CloverD-LinkUtility.pkg -target /" with administrator privileges'
echo "Install Utility-Package Done"
Sleep 1
cp -r ./Input/ActiveProfileSetting.plist /Private/tmp
Sleep 1
cp -r ./Input/AdvancedProfileSetting.plist $HOME/Library/Preferences
sleep 1
echo "Open PlistEdit"
osascript ./Input/PlistEdit.app
echo "PROGRESS:90"
sleep 1
echo "PROGRESS:100"
echo "DETAILS:SHOW"
Sleep 3
osascript <<EOD
  tell application "D-LinkUtility-Package"
      activate
  end tell
EOD
echo "Install Done"


  fi


# Exit if Canceled
if [ "$action" == "Cancel" ] ; then
  osascript -e 'do shell script "afplay './Sound/Funk.aiff' &> /dev/null &"'
  osascript -e 'display notification "Program closing" with title "'"$apptitle"'" subtitle "User cancelled"'
  echo "Program closing in 2 seconds User cancelled"
  Sleep 2
  echo "QUITAPP"
  exit 0
fi

fi

if [ "$action" == "Install /Library/Extensions" ] ; then
  osascript -e 'display notification "Program " with title "'"$apptitle"'" subtitle "User Select Install Library/Extensions"'
echo "DETAILS:HIDE"
echo "PROGRESS:0"
sleep 1
echo "PROGRESS:10"
sleep 1
echo "PROGRESS:20"
sleep 1
echo "PROGRESS:30"
echo "Install Progres."
Sleep 1
echo "PROGRESS:40"
sleep 1
echo "PROGRESS:50"
sleep 1
echo "PROGRESS:60"
sleep 2
echo "PROGRESS:80"
sleep 1
osascript <<EOD
  tell application "D-LinkUtility-Package"
      activate
  end tell
EOD
sleep 1
# Select Confirm Install
response=$(osascript -e 'tell app "System Events" to display dialog "
- - - - - - - - - - - - - - - - - - - - - - - - - -
By confirming that you agree to install this program on your current system, you will need to enter your password to complete the installation.
This program will install RT2870USBWirelessDriver.kext 
To the /Library/Extensions. You will need to click OK on the Security Popup.

Go to System Preferences → Security & Privacy and approve the Mediatek kernel extension.
You may need to restart your Mac for the driver to be loaded.
Plug the Mediatek USB adapter then Restart the Mac!		
- - - - - - - - - - - - - - - - - - - - - - - - - -
Cancel for Exit" buttons {"Cancel","Confirm Install"} default button 2 with title "'"$apptitle"' '"$version"'" with icon POSIX file "'"$iconfile"'"  ')

action=$(echo $response | cut -d ':' -f2)

 #  Post Installer is user select Confirm Install
  if [ "$action" == "Confirm Install" ] ; then
    # run the pkg
    echo "Install Package"
    cp -r ./Input/Wifi-Utility.app /Applications
    osascript -e 'tell application "System Events" to make login item at end with properties {path:"/Applications/Wifi-Utility.app", hidden:false}'
    Sleep 1
    Open -a /Applications/Wifi-Utility.app
    echo "Install D-LinkUtility.pkg"
    osascript -e 'do shell script "installer -allowUntrusted -verboseR -pkg ./Input/D-LinkUtility.pkg -target /" with administrator privileges'
echo "Install Utility-Package Done"
Sleep 1
cp -r ./Input/ActiveProfileSetting.plist /Private/tmp
Sleep 1
cp -r ./Input/AdvancedProfileSetting.plist $HOME/Library/Preferences
sleep 1
echo "Open PlistEdit"
osascript ./Input/PlistEdit.app
echo "PROGRESS:90"
sleep 1
echo "PROGRESS:100"
echo "DETAILS:SHOW"
Sleep 3
osascript <<EOD
  tell application "D-LinkUtility-Package"
      activate
  end tell
EOD
echo "Install Done"


  fi


# Exit if Canceled
if [ "$action" == "Cancel" ] ; then
  osascript -e 'do shell script "afplay './Sound/Funk.aiff' &> /dev/null &"'
  osascript -e 'display notification "Program closing" with title "'"$apptitle"'" subtitle "User cancelled"'
  echo "Program closing in 2 seconds User cancelled"
  Sleep 2
  echo "QUITAPP"
  exit 0
fi

fi


exit 0
